[supervisord]
nodaemon=true
logfile=/data/log/supervisord.log
logfile_maxbytes=0
pidfile=/run/supervisord.pid

[program:nginx]
command=/usr/sbin/nginx -g 'daemon off;'
stdout_logfile=/data/log/nginx-out.log
stdout_logfile_maxbytes=0
stderr_logfile=/data/log/nginx-err.log
stderr_logfile_maxbytes=0

[program:server]
command=/www-server/server -c /data/config.docker.yaml
stdout_logfile=/data/log/server-out.log
stdout_logfile_maxbytes=0
stderr_logfile=/data/log/server-err.log
stderr_logfile_maxbytes=0
